### ISSUE TITLE
Raspi 4 8GB need more Mhz :-)

### ISSUE THREAD

**Issue by Profex86** [yrzr/opnsense-tools#14]
Good day, the Raspberry Pi 4 with 8GB of RAM boosts to 1800MHz under Linux without overclocking. With the FreeBSD OpenSense version you provided, the Raspberry Pi does not go beyond 1500Mhz, resulting in approximately 800 Mbit throughput. The difference of 300Mhz is missing to fully utilize the Gigabit port. I have already tried various things like boost=1, but nothing was successful. Do you have a solution for this problem? Thank you for your work. Lg

**Comment by yrzr** [comment]
Please refer to my tests https://github.com/yrzr/opnsense-tools/issues/9#issuecomment-1809496846
