### ISSUE TITLE
`ftp.yrzr.tk` no longer reachable that plugins cannot be installed 域名解析失败，造成插件无法安装

### ISSUE THREAD

**Issue by tsz8899** [yrzr/opnsense-tools#15]
hi

近期yrzr.tk域名解析失效，造成：

无法访问https://yrzr.tk/opnsense-23-for-aarch64/
无法添加证书curl -k https://ftp.yrzr.tk/opnsense/fingerprint -o /usr/local/etc/pkg/fingerprints/OPNsense/trusted/ftp.yrzr.tk
无法添加软件源 安装插件
https://ftp.yrzr.tk/opnsense

**Comment by yrzr** [comment]
我的网站挂了，因为Freenom把我的域名状态改成"pending"了。我发了邮件但他们没有回复，考虑到Meta在跟他们打官司，我估计这个域名应该是恢复不了了。

你可以在`hosts`文件里把`ftp.yrzr.tk`指向`147.8.92.207`来临时解决你的问题。

My site is down. My domain name provider, Freenom, had my domain status changed to "pending" and did not respond to my emails. Considering Meta is suing Freenom, I don't expect they will have my domain recovered.

Still, you can change your `hosts` file and point `ftp.yrzr.tk` to `147.8.92.207` as a workaround.

**Comment by yrzr** [comment]
因为我不再能有效使用域名`yrzr.tk`，原本在使用的letsencrypt证书也无法续期了。

我已经将服务器的HTTPS重定向关了，现在可以使用`http://147.8.92.207/opnsense`替代原先的`https://ftp.yrzr.tk/opnsense`来访问我的软件源。

The domain `yrzr.tk` is no longer under my control. Therefore, I can not renew my SSL certification from Letsencrypt.

I have disabled the HTTPS redirect from the server. Now, you can use `http://147.8.92.207/opnsense` to replace `https://ftp.yrzr.tk/opnsense` and access my repo.
