### ISSUE TITLE
24.1-arm-aarch64-R6S 无法识别网卡

### ISSUE THREAD

**Issue by tsz8899** [yrzr/opnsense-tools#16]
github.com/edk2-porting/edk2-rk3588 0.9.1   OPNsense-23.7.9-arm-aarch64-R6S.img可以识别2个网卡，使用正常。

OPNsense-24.1-arm-aarch64-R6S.img后可以正常启动系统，但无法识别任何网卡。

**Comment by yrzr** [comment]
我试了一下，0.9.1的UEFI固件配我制作的24.1和24.1.5的两个镜像，都是能正常识别到两个re网卡的，哥们你先试试官方的系统启动网卡对不对
![20240409120644](https://github.com/yrzr/opnsense-tools/assets/8390472/13544180-201a-4cec-a5a6-d01c7e8effcd)
