### ISSUE TITLE
24.1 plug-ins

### ISSUE THREAD

**Issue by cyberpunked1985** [yrzr/opnsense-tools#19]
Plugins are restricted to 24.1.4? 

***GOT REQUEST TO INSTALL***
Currently running OPNsense 24.1 at Sun Mar 31 14:17:44 AWST 2024
Installation out of date. The update to opnsense-24.1.4 is required.
***DONE***

**Comment by yrzr** [comment]
I haven't built 24.1.4 yet. The latest version I have built is 24.1. Therefore, currently, you can only get OPNsense 24.1 pkgs from my site.

**Comment by cyberpunked1985** [comment]
ah yeah i see, i had the wrong url by accident, it is working now thanks
