### ISSUE TITLE
2.1 Repo - Updating OPNsense repository catalogue...

### ISSUE THREAD

**Issue by adamshumpisxxx** [yrzr/opnsense-tools#21]
I SSH into my R4S, I press 8 to enter the shell, I run your curl command, I modify the System > Firmware > Settings to (custom) as (other) isn't an option, I add "http://147.8.92.207/opnsense" without quotes and click Save. Status and Updates start spinning, Status eventually stops but Updates spin forever...Here is a screenshot of what I'm seeing:

![Screenshot 2024-05-28 163544](https://github.com/yrzr/opnsense-tools/assets/110312021/89aae3bf-3033-4941-ace4-41e23e47dfc9)

![Screenshot 2024-05-28 163536](https://github.com/yrzr/opnsense-tools/assets/110312021/ed693497-607a-4e2c-a712-8bd62f92e632)

What should I do? Thanks!

**Comment by adamshumpisxxx** [comment]
Are you watching me or something...?

![Screenshot 2024-05-28 165011](https://github.com/yrzr/opnsense-tools/assets/110312021/0863dd10-7450-4630-b5ce-cacddf27fe97)

This thing sits for over two hours and then I post this and all of a sudden within 5 minutes it finishes! Thanks!

**Comment by adamshumpisxxx** [comment]
Wait...maybe nevermind. I clicked Plugins and it went right back to spinning. 😞

**Comment by yrzr** [comment]
Just have to be patient sometimes ;)
