### ISSUE TITLE
Opnsense dont boot ARM

### ISSUE THREAD

**Issue by ghost** [yrzr/opnsense-tools#3]
Hi yrzr!
I downloaded the "OPNsense-23.7.1-arm-aarch64-RPI.img.xz" from Release
so far, so good. i put the Image with Balena Etcher on my External Drive (HDD)
i connect the HDD with the RPi 4B and start it but only a colorful Pic is showing like this:

![](https://i.stack.imgur.com/tFLUd.jpg)

**Comment by ChrisS1985ET** [comment]
https://forum.opnsense.org/index.php?topic=12186.msg148970#msg148970

**Comment by mariusherta** [comment]
Try the other HDMI port from the Raspberry Pi.

**Comment by ghost** [comment]
> Try the other HDMI port from the Raspberry Pi.

I became a Output

**Comment by mariusherta** [comment]
> > Try the other HDMI port from the Raspberry Pi.
> 
> I became a Output

I'm sorry that you became an output, however try plugging the hdmi cable into the port next to the usb-c.
